# Generated by cstruct-stubgen
from typing import BinaryIO, Literal, TypeAlias, overload

import dissect.cstruct as __cs__

class _c_tibx(__cs__.cstruct):
    PAGE_SIZE: Literal[4096] = ...
    class PageType(__cs__.Enum):
        ARCH = ...
        ARCI = ...
        LEAF = ...
        LDIR = ...
        GOLOMB = ...
        DATA = ...

    class EncrAlg(__cs__.Enum):
        NONE = ...
        AES_128_CBC = ...
        AES_192_CBC = ...
        AES_256_CBC = ...
        GOST2015 = ...
        AES_128_GCM = ...
        AES_192_GCM = ...
        AES_256_GCM = ...

    class ComprLvl(__cs__.Enum):
        NONE = ...
        LOW = ...
        NORMAL = ...
        HIGH = ...

    class page_header(__cs__.Structure):
        marker: _c_tibx.uint8
        type: _c_tibx.PageType
        _pad: _c_tibx.uint16
        crc32c: _c_tibx.uint32
        @overload
        def __init__(self, marker: _c_tibx.uint8 | None = ..., type: _c_tibx.PageType | None = ..., _pad: _c_tibx.uint16 | None = ..., crc32c: _c_tibx.uint32 | None = ...): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class arch_header(__cs__.Structure):
        magic: __cs__.CharArray
        header_size: _c_tibx.uint32
        header_version: _c_tibx.uint16
        compr_lvl: _c_tibx.ComprLvl
        encr_alg: _c_tibx.EncrAlg
        dedup: _c_tibx.uint8
        hash_alg: _c_tibx.uint8
        chunking_alg: _c_tibx.uint8
        hash_window_width: _c_tibx.uint8
        created_ms: _c_tibx.uint64
        modified_ms: _c_tibx.uint64
        archive_uuid: __cs__.CharArray
        @overload
        def __init__(self, magic: __cs__.CharArray | None = ..., header_size: _c_tibx.uint32 | None = ..., header_version: _c_tibx.uint16 | None = ..., compr_lvl: _c_tibx.ComprLvl | None = ..., encr_alg: _c_tibx.EncrAlg | None = ..., dedup: _c_tibx.uint8 | None = ..., hash_alg: _c_tibx.uint8 | None = ..., chunking_alg: _c_tibx.uint8 | None = ..., hash_window_width: _c_tibx.uint8 | None = ..., created_ms: _c_tibx.uint64 | None = ..., modified_ms: _c_tibx.uint64 | None = ..., archive_uuid: __cs__.CharArray | None = ...): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class arch_superblock(__cs__.Structure):
        header: _c_tibx.page_header
        body: _c_tibx.arch_header
        @overload
        def __init__(self, header: _c_tibx.page_header | None = ..., body: _c_tibx.arch_header | None = ...): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class tlv_header(__cs__.Structure):
        length: _c_tibx.uint32
        @overload
        def __init__(self, length: _c_tibx.uint32 | None = ...): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class segment_header(__cs__.Structure):
        magic: __cs__.CharArray
        version: _c_tibx.uint16
        length: _c_tibx.uint32
        zlength: _c_tibx.uint32
        key_id: _c_tibx.uint32
        compression: _c_tibx.uint16
        cache: _c_tibx.uint16
        @overload
        def __init__(self, magic: __cs__.CharArray | None = ..., version: _c_tibx.uint16 | None = ..., length: _c_tibx.uint32 | None = ..., zlength: _c_tibx.uint32 | None = ..., key_id: _c_tibx.uint32 | None = ..., compression: _c_tibx.uint16 | None = ..., cache: _c_tibx.uint16 | None = ...): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class segment_cbc_header(__cs__.Structure):
        iv: __cs__.CharArray
        @overload
        def __init__(self, iv: __cs__.CharArray | None = ...): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class segment_gcm_header(__cs__.Structure):
        iv: __cs__.CharArray
        tag: __cs__.CharArray
        @overload
        def __init__(self, iv: __cs__.CharArray | None = ..., tag: __cs__.CharArray | None = ...): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class lz4_block_header(__cs__.Structure):
        compressed_size: _c_tibx.uint32
        uncompressed_size: _c_tibx.uint32
        @overload
        def __init__(self, compressed_size: _c_tibx.uint32 | None = ..., uncompressed_size: _c_tibx.uint32 | None = ...): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class lsm_superblock(__cs__.Structure):
        magic: __cs__.CharArray
        format_version: _c_tibx.uint8
        ctree_count_minus_2: _c_tibx.uint8
        ctree_max_minus_2: _c_tibx.uint8
        _reserved0: _c_tibx.uint8
        seq: _c_tibx.uint32
        ctree_size_hint: _c_tibx.uint32
        key_length: _c_tibx.uint32
        value_length: _c_tibx.uint32
        @overload
        def __init__(self, magic: __cs__.CharArray | None = ..., format_version: _c_tibx.uint8 | None = ..., ctree_count_minus_2: _c_tibx.uint8 | None = ..., ctree_max_minus_2: _c_tibx.uint8 | None = ..., _reserved0: _c_tibx.uint8 | None = ..., seq: _c_tibx.uint32 | None = ..., ctree_size_hint: _c_tibx.uint32 | None = ..., key_length: _c_tibx.uint32 | None = ..., value_length: _c_tibx.uint32 | None = ...): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class ctree_ref(__cs__.Structure):
        offset: _c_tibx.uint64
        num_pages: _c_tibx.uint64
        item_count: _c_tibx.uint32
        _reserved: _c_tibx.uint32
        max_key_or_size: _c_tibx.uint64
        @overload
        def __init__(self, offset: _c_tibx.uint64 | None = ..., num_pages: _c_tibx.uint64 | None = ..., item_count: _c_tibx.uint32 | None = ..., _reserved: _c_tibx.uint32 | None = ..., max_key_or_size: _c_tibx.uint64 | None = ...): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class lsm_memtree_header(__cs__.Structure):
        encoding: _c_tibx.uint8
        _reserved: _c_tibx.uint8
        node_count: _c_tibx.uint16
        extra_len: _c_tibx.uint32
        pages_total: _c_tibx.uint32
        @overload
        def __init__(self, encoding: _c_tibx.uint8 | None = ..., _reserved: _c_tibx.uint8 | None = ..., node_count: _c_tibx.uint16 | None = ..., extra_len: _c_tibx.uint32 | None = ..., pages_total: _c_tibx.uint32 | None = ...): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class lsm_page_header(__cs__.Structure):
        magic: __cs__.CharArray
        version: _c_tibx.uint8
        encoding: _c_tibx.uint8
        cell_count: _c_tibx.uint16
        uncompressed_size: _c_tibx.uint32
        on_disk_size: _c_tibx.uint32
        key_size_param: _c_tibx.uint32
        _sequence_id: __cs__.CharArray
        @overload
        def __init__(self, magic: __cs__.CharArray | None = ..., version: _c_tibx.uint8 | None = ..., encoding: _c_tibx.uint8 | None = ..., cell_count: _c_tibx.uint16 | None = ..., uncompressed_size: _c_tibx.uint32 | None = ..., on_disk_size: _c_tibx.uint32 | None = ..., key_size_param: _c_tibx.uint32 | None = ..., _sequence_id: __cs__.CharArray | None = ...): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class lsm_cell_group_header(__cs__.Structure):
        count: _c_tibx.uint8
        alive: _c_tibx.uint24
        @overload
        def __init__(self, count: _c_tibx.uint8 | None = ..., alive: _c_tibx.uint24 | None = ...): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class ldir_value(__cs__.Structure):
        child_offset: _c_tibx.uint64
        @overload
        def __init__(self, child_offset: _c_tibx.uint64 | None = ...): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class data_map_key(__cs__.Structure):
        volume_id: _c_tibx.uint64
        source_offset: _c_tibx.uint64
        extent_length: _c_tibx.uint24
        slice_id: _c_tibx.uint32
        extent_id: _c_tibx.uint64
        @overload
        def __init__(self, volume_id: _c_tibx.uint64 | None = ..., source_offset: _c_tibx.uint64 | None = ..., extent_length: _c_tibx.uint24 | None = ..., slice_id: _c_tibx.uint32 | None = ..., extent_id: _c_tibx.uint64 | None = ...): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class data_map_value(__cs__.Structure):
        segment_id: _c_tibx.uint64
        extent_index: _c_tibx.uint16
        @overload
        def __init__(self, segment_id: _c_tibx.uint64 | None = ..., extent_index: _c_tibx.uint16 | None = ...): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class segment_map_key(__cs__.Structure):
        segment_id: _c_tibx.uint64
        @overload
        def __init__(self, segment_id: _c_tibx.uint64 | None = ...): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class segment_map_value(__cs__.Structure):
        page_count: __cs__.CharArray
        page_offset: _c_tibx.uint32
        slice_id: _c_tibx.uint32
        hash: __cs__.CharArray
        @overload
        def __init__(self, page_count: __cs__.CharArray | None = ..., page_offset: _c_tibx.uint32 | None = ..., slice_id: _c_tibx.uint32 | None = ..., hash: __cs__.CharArray | None = ...): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class slice_key(__cs__.Structure):
        slice_id: _c_tibx.uint32
        @overload
        def __init__(self, slice_id: _c_tibx.uint32 | None = ...): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class slice_record(__cs__.Structure):
        guid: __cs__.CharArray
        created_ms: _c_tibx.uint64
        modified_ms: _c_tibx.uint64
        @overload
        def __init__(self, guid: __cs__.CharArray | None = ..., created_ms: _c_tibx.uint64 | None = ..., modified_ms: _c_tibx.uint64 | None = ...): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class wrapped_key(__cs__.Structure):
        format: _c_tibx.uint8
        alg: _c_tibx.uint8
        iter_log2: _c_tibx.uint8
        _reserved: _c_tibx.uint8
        salt: __cs__.CharArray
        @overload
        def __init__(self, format: _c_tibx.uint8 | None = ..., alg: _c_tibx.uint8 | None = ..., iter_log2: _c_tibx.uint8 | None = ..., _reserved: _c_tibx.uint8 | None = ..., salt: __cs__.CharArray | None = ...): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class file_table_entry(__cs__.Structure):
        index: _c_tibx.uint32
        byte_offset: _c_tibx.uint64
        @overload
        def __init__(self, index: _c_tibx.uint32 | None = ..., byte_offset: _c_tibx.uint64 | None = ...): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

# Technically `c_tibx` is an instance of `_c_tibx`, but then we can't use it in type hints
c_tibx: TypeAlias = _c_tibx

class _c_boot(__cs__.cstruct):
    class ntfs_boot_sector(__cs__.Structure):
        jump: __cs__.CharArray
        oem_id: __cs__.CharArray
        bytes_per_sector: _c_boot.uint16
        _unused: __cs__.CharArray
        total_sectors: _c_boot.uint64
        @overload
        def __init__(self, jump: __cs__.CharArray | None = ..., oem_id: __cs__.CharArray | None = ..., bytes_per_sector: _c_boot.uint16 | None = ..., _unused: __cs__.CharArray | None = ..., total_sectors: _c_boot.uint64 | None = ...): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class exfat_boot_sector(__cs__.Structure):
        jump: __cs__.CharArray
        fs_name: __cs__.CharArray
        _must_be_zero: __cs__.CharArray
        partition_offset: _c_boot.uint64
        volume_length: _c_boot.uint64
        _unused: __cs__.CharArray
        bytes_per_sector_shift: _c_boot.uint8
        @overload
        def __init__(self, jump: __cs__.CharArray | None = ..., fs_name: __cs__.CharArray | None = ..., _must_be_zero: __cs__.CharArray | None = ..., partition_offset: _c_boot.uint64 | None = ..., volume_length: _c_boot.uint64 | None = ..., _unused: __cs__.CharArray | None = ..., bytes_per_sector_shift: _c_boot.uint8 | None = ...): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class fat_boot_sector(__cs__.Structure):
        jump: __cs__.CharArray
        oem_id: __cs__.CharArray
        bytes_per_sector: _c_boot.uint16
        sectors_per_cluster: _c_boot.uint8
        reserved_sectors: _c_boot.uint16
        fat_count: _c_boot.uint8
        root_entries: _c_boot.uint16
        total_sectors_16: _c_boot.uint16
        media: _c_boot.uint8
        fat_size_16: _c_boot.uint16
        sectors_per_track: _c_boot.uint16
        heads: _c_boot.uint16
        hidden_sectors: _c_boot.uint32
        total_sectors_32: _c_boot.uint32
        _fat16_ext: __cs__.CharArray
        fs_type_16: __cs__.CharArray
        _fat32_ext: __cs__.CharArray
        fs_type_32: __cs__.CharArray
        @overload
        def __init__(self, jump: __cs__.CharArray | None = ..., oem_id: __cs__.CharArray | None = ..., bytes_per_sector: _c_boot.uint16 | None = ..., sectors_per_cluster: _c_boot.uint8 | None = ..., reserved_sectors: _c_boot.uint16 | None = ..., fat_count: _c_boot.uint8 | None = ..., root_entries: _c_boot.uint16 | None = ..., total_sectors_16: _c_boot.uint16 | None = ..., media: _c_boot.uint8 | None = ..., fat_size_16: _c_boot.uint16 | None = ..., sectors_per_track: _c_boot.uint16 | None = ..., heads: _c_boot.uint16 | None = ..., hidden_sectors: _c_boot.uint32 | None = ..., total_sectors_32: _c_boot.uint32 | None = ..., _fat16_ext: __cs__.CharArray | None = ..., fs_type_16: __cs__.CharArray | None = ..., _fat32_ext: __cs__.CharArray | None = ..., fs_type_32: __cs__.CharArray | None = ...): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class ext_superblock(__cs__.Structure):
        inodes_count: _c_boot.uint32
        blocks_count: _c_boot.uint32
        _unused0: __cs__.CharArray
        log_block_size: _c_boot.uint32
        _unused1: __cs__.CharArray
        magic: _c_boot.uint16
        @overload
        def __init__(self, inodes_count: _c_boot.uint32 | None = ..., blocks_count: _c_boot.uint32 | None = ..., _unused0: __cs__.CharArray | None = ..., log_block_size: _c_boot.uint32 | None = ..., _unused1: __cs__.CharArray | None = ..., magic: _c_boot.uint16 | None = ...): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

# Technically `c_boot` is an instance of `_c_boot`, but then we can't use it in type hints
c_boot: TypeAlias = _c_boot
